package EsBodyMeasurements

import ehoul.study.pojo.EsBodyMeasurements;
import ehoul.study.BMDCheckResult;

rule "length unit"

    when
        $bmd : EsBodyMeasurements(lengthUnit == null);
        $result:BMDCheckResult();
    then
        $result.setStatus(false);
        $result.setMessage("量体数据长度单位为空");
end
rule "2"
    when
        $bmd : EsBodyMeasurements();
    then
        $bmd.setMeasurementRecordId(1234567);
        System.out.println("规则中打印日志：校验通过!");
end